"""Xaytune control-plane core.

Domain types, identifiers, state machines and errors for the experiment control
plane. This package is deliberately free of ML and runtime dependencies — no
torch, transformers, peft, trl, ray, torchft, kubernetes, mlflow or wandb — so
that a controller host or client can import it without the training stack
installed (ADR-010).

That boundary is enforced by ``tests/test_core/test_architecture.py``.
"""

from __future__ import annotations

from xaytune.core.capabilities import (
    CapabilityDocument,
    CapabilityRequirements,
    PluginDescriptor,
)
from xaytune.core.clock import utc_now
from xaytune.core.domain import (
    Action,
    ActionOutcome,
    ActionTarget,
    AdapterSpec,
    AlgorithmSpec,
    BudgetSpec,
    CandidateSpec,
    CandidateSpecSnapshot,
    CheckpointIntent,
    DataSpec,
    DomainEvent,
    EnvironmentSpec,
    ExecutionOverride,
    Experiment,
    ExperimentNode,
    LRScheduleSpec,
    MetricConstraint,
    ModelSpec,
    Objective,
    ObjectiveMetric,
    OptimizationSpec,
    OptimizerSpec,
    OutboxRecord,
    PrecisionSpec,
    RewardSpec,
    Run,
    RunAttempt,
    RuntimeOperation,
    RuntimeOperationTarget,
    ScheduledIntervention,
    TrainingKind,
    TrainingSchedule,
    TrainingSpec,
    artifact_lineage_fingerprint,
    candidate_identity_v1,
    candidate_identity_v2,
    run_history_fingerprint,
)
from xaytune.core.errors import (
    ConcurrentModificationError,
    DomainError,
    InvalidIdError,
    InvalidTransitionError,
    XaytuneError,
)
from xaytune.core.execution import (
    ArtifactInput,
    ArtifactOutput,
    CheckpointExecutionContract,
    CompilerIdentity,
    ContainerSpec,
    DependencySpec,
    EntrypointSpec,
    ResolvedExecutionPlan,
    ResourceRequirements,
    SecretRef,
    TelemetryContract,
    TrainingExecutionSpec,
)
from xaytune.core.ids import (
    ActionId,
    ArtifactId,
    CheckpointId,
    DecisionId,
    EvaluationId,
    EventId,
    ExperimentId,
    ExperimentNodeId,
    IncidentId,
    OperationId,
    RunAttemptId,
    RunId,
    TypedId,
)
from xaytune.core.observability import (
    CorrelationContext,
    ObservabilitySpec,
    ProfilerSpec,
    RedactionPolicy,
    TraceContext,
    TracingSpec,
)
from xaytune.core.refs import (
    Actor,
    ArtifactRef,
    CheckpointRef,
    ControllerHostRef,
    DatasetRef,
    ModelRef,
    ResourceUsage,
    RuntimeRef,
)
from xaytune.core.resume import (
    CheckpointBoundary,
    CheckpointStateManifest,
    DataCursor,
    DataResume,
    ResumeGuarantee,
    RNGState,
    SamplerState,
    StateRestore,
    WorkerRNGState,
)
from xaytune.core.sinks import (
    EventSink,
)
from xaytune.core.state import (
    ACTION_MACHINE,
    ATTEMPT_MACHINE,
    EXPERIMENT_MACHINE,
    NODE_MACHINE,
    RUN_MACHINE,
    ActionStatus,
    ExperimentNodeStatus,
    ExperimentStatus,
    RunAttemptStatus,
    RunStatus,
    StateMachine,
)

__all__ = [
    "CorrelationContext",
    "ObservabilitySpec",
    "ProfilerSpec",
    "RedactionPolicy",
    "TraceContext",
    "TracingSpec",
    "CheckpointBoundary",
    "CheckpointStateManifest",
    "DataCursor",
    "DataResume",
    "ResumeGuarantee",
    "RNGState",
    "SamplerState",
    "StateRestore",
    "WorkerRNGState",
    "EventSink",
    "Action",
    "ACTION_MACHINE",
    "ActionId",
    "ActionOutcome",
    "ActionStatus",
    "ActionTarget",
    "Actor",
    "AdapterSpec",
    "AlgorithmSpec",
    "artifact_lineage_fingerprint",
    "ArtifactId",
    "ArtifactInput",
    "ArtifactOutput",
    "ArtifactRef",
    "ATTEMPT_MACHINE",
    "BudgetSpec",
    "candidate_identity_v1",
    "candidate_identity_v2",
    "CandidateSpec",
    "CandidateSpecSnapshot",
    "CapabilityDocument",
    "CapabilityRequirements",
    "CheckpointExecutionContract",
    "CheckpointId",
    "CheckpointIntent",
    "CheckpointRef",
    "CompilerIdentity",
    "ConcurrentModificationError",
    "ContainerSpec",
    "ControllerHostRef",
    "DatasetRef",
    "DataSpec",
    "DecisionId",
    "DependencySpec",
    "DomainError",
    "DomainEvent",
    "EntrypointSpec",
    "EnvironmentSpec",
    "EvaluationId",
    "EventId",
    "ExecutionOverride",
    "Experiment",
    "EXPERIMENT_MACHINE",
    "ExperimentId",
    "ExperimentNode",
    "ExperimentNodeId",
    "ExperimentNodeStatus",
    "ExperimentStatus",
    "IncidentId",
    "InvalidIdError",
    "InvalidTransitionError",
    "LRScheduleSpec",
    "MetricConstraint",
    "ModelRef",
    "ModelSpec",
    "NODE_MACHINE",
    "Objective",
    "ObjectiveMetric",
    "OperationId",
    "OptimizationSpec",
    "OptimizerSpec",
    "OutboxRecord",
    "PluginDescriptor",
    "PrecisionSpec",
    "ResolvedExecutionPlan",
    "ResourceRequirements",
    "ResourceUsage",
    "RewardSpec",
    "Run",
    "run_history_fingerprint",
    "RUN_MACHINE",
    "RunAttempt",
    "RunAttemptId",
    "RunAttemptStatus",
    "RunId",
    "RunStatus",
    "RuntimeOperation",
    "RuntimeOperationTarget",
    "RuntimeRef",
    "ScheduledIntervention",
    "SecretRef",
    "StateMachine",
    "TelemetryContract",
    "TrainingExecutionSpec",
    "TrainingKind",
    "TrainingSchedule",
    "TrainingSpec",
    "TypedId",
    "utc_now",
    "XaytuneError",
]
