"""Control-plane domain aggregates."""

from __future__ import annotations

from xaytune.core.domain.action import (
    Action,
    ActionOutcome,
    ActionTarget,
    ActionTargetKind,
    ActionType,
    UnknownActionTypeError,
    register_action_type,
    registered_action_types,
)
from xaytune.core.domain.candidate import (
    AdapterSpec,
    AlgorithmSpec,
    CandidateSpec,
    CheckpointIntent,
    DataSpec,
    EnvironmentSpec,
    LRScheduleSpec,
    ModelSpec,
    OptimizationSpec,
    OptimizerSpec,
    PrecisionSpec,
    RewardSpec,
    ScheduledIntervention,
    TrainingKind,
    TrainingSchedule,
    TrainingSpec,
    candidate_identity_v1,
    candidate_identity_v2,
)
from xaytune.core.domain.event import (
    DomainEvent,
    OutboxRecord,
    OutboxState,
)
from xaytune.core.domain.experiment import (
    CandidateSpecSnapshot,
    Experiment,
    ExperimentNode,
)
from xaytune.core.domain.objective import (
    BudgetSpec,
    MetricConstraint,
    Objective,
    ObjectiveMetric,
)
from xaytune.core.domain.operation import (
    OperationState,
    OperationTargetKind,
    OperationType,
    RuntimeOperation,
    RuntimeOperationTarget,
)
from xaytune.core.domain.run import (
    ExecutionOverride,
    ExecutionOverrideKind,
    Run,
    RunAttempt,
    artifact_lineage_fingerprint,
    run_history_fingerprint,
)

__all__ = [
    "Action",
    "ActionOutcome",
    "ActionTarget",
    "ActionTargetKind",
    "ActionType",
    "AdapterSpec",
    "AlgorithmSpec",
    "artifact_lineage_fingerprint",
    "BudgetSpec",
    "candidate_identity_v1",
    "candidate_identity_v2",
    "CandidateSpec",
    "CandidateSpecSnapshot",
    "CheckpointIntent",
    "DataSpec",
    "DomainEvent",
    "EnvironmentSpec",
    "ExecutionOverride",
    "ExecutionOverrideKind",
    "Experiment",
    "ExperimentNode",
    "LRScheduleSpec",
    "MetricConstraint",
    "ModelSpec",
    "Objective",
    "ObjectiveMetric",
    "OperationState",
    "OperationTargetKind",
    "OperationType",
    "OptimizationSpec",
    "OptimizerSpec",
    "OutboxRecord",
    "OutboxState",
    "PrecisionSpec",
    "register_action_type",
    "registered_action_types",
    "RewardSpec",
    "Run",
    "run_history_fingerprint",
    "RunAttempt",
    "RuntimeOperation",
    "RuntimeOperationTarget",
    "ScheduledIntervention",
    "TrainingKind",
    "TrainingSchedule",
    "TrainingSpec",
    "UnknownActionTypeError",
]
